### PR TITLE
Changed bootstrap.css from nagging on Github to using cdnjs

### PR DESCRIPTION
**Pull request by kevinsimper**

### CODE REVIEW

**Comment by potomak** [comment]
:+1:

**Comment by nnarhinen** [comment]
is this project abandoned?

**Comment by starwed** [comment]
@nnarhinen  The folk who were hosting the components site no longer have the time to maintain it, apparently.

See [crafty issue #529](https://github.com/craftyjs/Crafty/issues/529)

**Comment by potomak** [comment]
I think this should be closed due to #8.

**Pull request closed without merging**
